services:
  nginx:
    build:
      context: /home/ataoufik/Desktop/inception/srcs/requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/wordpress
    depends_on:
      - wordpress
      - mariadb
    restart: on-failure
    networks:
      - my_network

  wordpress:
    build: 
      context: /home/ataoufik/Desktop/inception/srcs/requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/wordpress
    depends_on:
      - mariadb
      - redis
    restart: on-failure
    networks:
      - my_network

  mariadb:
    build: 
      context: /home/ataoufik/Desktop/inception/srcs/requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: on-failure
    volumes:
      - DB:/var/lib/mysql
    networks:
      - my_network
  redis:
    build: 
      context: /home/ataoufik/Desktop/inception/srcs/requirements/bonus/redis
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
volumes:
  DB:
  WordPress:
