services:
  nginx:
    build:
      context: /home/ataoufik/Desktop/inception/srcs/requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/wordpress
    depends_on:
      - wordpress
      - mariadb
    restart: on-failure
    networks:
      - my_network
  wordpress:
    build: 
      context: /home/ataoufik/Desktop/inception/srcs/requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - WordPress:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure
    networks:
      - my_network
  redis:
    build: 
      context: /home/ataoufik/Desktop/inception/srcs/requirements/bonus/redis
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    depends_on:
      - wordpress
      - mariadb
    networks:
      - my_network
  adminer:
    build:
      context: /home/ataoufik/Desktop/inception/srcs/requirements/bonus/adminer
    container_name: adminer
    depends_on:
      - mariadb 
    ports:
      - "8080:8080"
    networks:
      - my_network
  portainer:
    build:
      context: /home/ataoufik/Desktop/inception/srcs/requirements/bonus/portainer
    container_name: portainer
    env_file:
      - .env
    ports:
      - "9443:9443"
    networks:
      - my_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  ftp:
    build: 
      context: /home/ataoufik/Desktop/inception/srcs/requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "40000-40100:40000-40100"
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - my_network
    volumes:
      - WordPress:${DIR_FTP}
  web:
    build: 
      context: /home/ataoufik/Desktop/inception/srcs/requirements/bonus/web
    container_name: web
    ports:
      - "80:80"
    networks:
      - my_network
  mariadb:
    build: 
      context: /home/ataoufik/Desktop/inception/srcs/requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    restart: on-failure
    volumes:
      - DB:/var/lib/mysql
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
volumes:
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ataoufik/data/db
  WordPress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ataoufik/data/wordpress
