service mariadb start
mysql -u root --password=${PASSWORD_ROOT}<<EOF
CREATE DATABASE ${NAME_DATABASE};
CREATE USER '${NAME_USER}'@'localhost' IDENTIFIED BY '${USER_PASSWORD}';
GRANT ALL PRIVILEGES ON ${NAME_DATABASE}.* TO '${NAME_USER}'@'localhost';
FLUSH PRIVILEGES;
EOF
